Add stable staging environment inputs
Azure/static-web-apps-deploy pull request #14
Opened 2022-03-09 20:16 UTC by mishapos

2022-04-12 23:32 UTC, annikel approved these changes

2022-04-12 23:32 UTC, annikel commented on action.yml
> +    description: "Production branch. Deploys from other branches will be considered staging environments."
Is it Deploys or Deployments?

2022-04-12 23:46 UTC, mishapos commented on action.yml
> +    description: "Production branch. Deploys from other branches will be considered staging environments."
`Deployments` is better. Thank you!

2022-04-13 15:58 UTC, joslinmicrosoft requested changes

2022-04-13 15:58 UTC, joslinmicrosoft commented on action.yml
>      description: "Skips the build step for the Azure Functions source code if set to true."
let's add back the `required: false` for this one

2022-04-13 15:58 UTC, joslinmicrosoft commented on action.yml
> +
nit: remove this newline

2022-04-13 16:04 UTC, mishapos commented on action.yml
>      description: "Skips the build step for the Azure Functions source code if set to true."
Added it back. thanks for the good catch!

2022-04-20 15:55 UTC, miwebst commented on action.yml
> +    description: "Production branch. Deployments from other branches will be considered preview environments."
Lets add "When specified," before deployments

2022-04-20 15:56 UTC, miwebst commented on action.yml
> +    description: "Explicit name of Azure Static Web Apps environment for this deployment."
I feel like this should be something like "Name of the Azure Static Web Apps environment to deploy to"

2022-04-20 17:02 UTC, miwebst approved these changes

2022-04-21 22:00 UTC, joslinmicrosoft approved these changes

2022-04-21 22:01 UTC, merged