feat: add is_static_export flag.
Azure/static-web-apps-deploy pull request #15
Opened 2022-04-20 06:59 UTC by tkamesh

2022-05-04 15:38 UTC, joslinmicrosoft requested changes

2022-05-04 15:38 UTC, joslinmicrosoft commented on action.yml
> +    description: "Indicates site is static export"
Can we make this consistent with the other boolean configurations, something like "Indicates site is static export **_if set to true._**"?

Also, is this only for NextJS (if so, can we mention it in the description)? And is "static export" a standard term? In searches I'm finding "Static HTML Export".

2022-05-04 15:38 UTC, joslinmicrosoft commented on action.yml
> +  is_static_export:
Can you please pull down the latest changes from Azure:v1, just so we can see exactly what the resulting change will look like once merged?

2022-05-04 17:18 UTC, joslinmicrosoft commented on action.yml
> +  is_static_export:
nit: now that this is pulled with the latest changes, can we move this to the bottom (after `deployment_environment`)? just to be consistent and append at the end rather than middle. unless there's a good reason to have it here

2022-05-05 15:25 UTC, simonaco commented on action.yml
> +    description: "Indicates site is static export"
We can update to: "Indicates you are using `next export` to generate a static site if set to true."

2022-05-05 15:53 UTC, joslinmicrosoft approved these changes

2022-05-05 16:30 UTC, merged